Add Hono-Prisma-Postgres Todo Application Example (#2395)
keploy/samples-typescript pull request #69
Opened 2024-12-25 12:54 UTC by Vibgitcode27

# Pull Request: Add Hono-Prisma-Postgres Todo Application Example (#2395)

## Description
This PR resolves issue #2395 by adding a sample **Hono-Prisma-Postgres** Todo application to the `samples-typescript` repository. This example demonstrates how to use the **Hono** web framework with **Prisma**, **PostgreSQL**, and **Keploy** for end-to-end API testing.

## Changes Made
- Added a `hono-prisma-postgres` directory containing:
  - Source code for the Sample application.
  - A detailed `README.md` explaining the setup and usage of the project.
- Integrated Keploy for recording and running test cases.

## How This Resolves Issue #2395
The issue highlights the lack of a **Hono** example in the TypeScript samples repository. This PR introduces an example showcasing the following:
- **Hono Framework**: A fast-growing web framework.
- **Keploy Integration**: Guides developers in recording and testing API calls effortlessly.
- **Database Support**: Uses PostgreSQL with Prisma for robust and scalable data handling.

## Checklist
- [x] Issue #2395 resolved.
- [x] Application tested locally.
- [x] Documentation (README.md) added.

---

## Linked Issue
Resolves [#2395](https://github.com/keploy/keploy/issues/2395)

#
Please let me know if further changes are needed or if there are additional requirements for merging this PR.

2024-12-26 08:01 UTC, khareyash05 requested changes
Hi! Please address the comments

2024-12-26 08:01 UTC, khareyash05 commented on hono-prisma-postgres/README.md
Can you please add the docker configuration for the same as well

2024-12-26 08:01 UTC, khareyash05 commented on hono-prisma-postgres/index.ts
is this file needed?

2024-12-27 12:19 UTC, Vibgitcode27 commented
@khareyash05 Added Docker configurations and removed index.ts.I didn't remove it earlier because its defualt file generated when project is initialized.

2024-12-29 14:36 UTC, khareyash05 requested changes
Hey looks fine! Just could you please remove the keploy folder .

2024-12-29 16:10 UTC, Vibgitcode27 commented
@khareyash05 Done!

2025-01-24 06:20 UTC, khareyash05 approved these changes

2025-01-24 06:20 UTC, merged